- hosts: localhost
  become: true
  tasks:

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: /home/raist/ansible/dotfiles/btop.conf
      dest: /home/raist/btop.conf
      owner: raist
      group: raist
      mode: '0644'
  